name: Update Latest Repo

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Get latest public repo
      id: latest
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const username = context.repo.owner;
          const repos = await github.rest.repos.listForUser({
            username,
            sort: "updated",
            per_page: 1,
          });

          const latestRepo = repos.data[0];
          const badge = `<img src="https://github-readme-stats.vercel.app/api/pin/?username=${username}&repo=${latestRepo.name}&theme=tokyonight&hide_border=true" />`;
          const link = `<a href="https://github.com/${username}/${latestRepo.name}">${badge}</a>`;

          return link;

    - name: Update README
      run: |
        content=$(<README.md)
        new_section="${{ steps.latest.outputs.result }}"
        updated=$(echo "$content" | awk '
          BEGIN { in_section=0 }
          /<!--START_SECTION:latest-repo-->/ { print; print new_section; in_section=1; next }
          /<!--END_SECTION:latest-repo-->/ { in_section=0 }
          !in_section { print }
        ' new_section="$new_section")

        echo "$updated" > README.md

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add README.md
        git commit -m "🔄 auto-update latest repo" || echo "No changes to commit"
        git push
